group:
    resource: "@GroupBundle/Controller/"
    type:     annotation
    prefix:   /group

notification:
    resource: "@NotificationBundle/Controller/"
    type:     annotation
    prefix:   /notif

notification_api:
    resource: "@NotificationBundle/Controller/Api/"
    type:     annotation

payement_api:
    resource: "@PayementBundle/Controller/Api/"
    type:     annotation

payement:
    resource: "@PayementBundle/Controller/"
    type:     annotation
    prefix:   /payement

app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_message:
    resource: "@FOSMessageBundle/Resources/config/routing.xml"
    prefix: /messanger